// Kategori listesi
const List<String> categories = [
  'Kahve ve Sohbet',
  'Kitap Buluşmaları',
  'Dil ve Kültür Değişimi',
  'Spor Faaliyetleri',
  'Halısaha Aktiviteleri',
  'Doğa Faaliyetleri',
  'Fitness ve Egzersiz',
  'Sanat ve Tarihi Geziler',
  'Film ve Dizi Buluşmaları',
  'Dans Buluşmaları',
  'Müzik Faaliyetleri',
  'Konser Buluşmaları',
  'Parti ve Eğlence',
  'Mutfak Sanatları',
  'Eğitim Faaliyetleri',
  'Araştırma Grupları',
  'Video Oyunu Buluşmaları',
  'El Sanatları',
  'Yazılımcı Buluşmaları',
  'Yoga ve Meditasyon',
  'Fotoğrafçılık Faaliyetleri',
  'Evcil Hayvan Buluşmaları',
  'Motosiklet Grupları',
  'Araba Grupları',
  'Moda ve Giyim',
  'Çevrimiçi Etkinlikler',
  'Çevrimiçi Oyun Turnuvaları',
  'Seyahat Etkinlikleri',
  'Oda Paylaşımı ve Emlak',
  'Araba Kiralama, Alım/Satım',
  'Eşya Alım/Satım',
  'Diğer',
];
