// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvfALCYuW9Ux-Qe0NpxomB25DcslTdz6w',
    appId: '1:904894098695:android:078e41f4d0f2928617a9a2',
    messagingSenderId: '904894098695',
    projectId: 'orti-app-2c44b',
    storageBucket: 'orti-app-2c44b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtjiRluvhVW0xQGyLrXvLZ9aH8G_cqMVw',
    appId: '1:904894098695:ios:04244f924e4a970e17a9a2',
    messagingSenderId: '904894098695',
    projectId: 'orti-app-2c44b',
    storageBucket: 'orti-app-2c44b.appspot.com',
    androidClientId: '904894098695-8ts1opkceqip396fs9hqpuvvmdgvuokm.apps.googleusercontent.com',
    iosClientId: '904894098695-dijlrg3vokogs6kt3r0af41tieqfq7vg.apps.googleusercontent.com',
    iosBundleId: 'com.alpkaan.dostumolsana',
  );
}
